# Generated by Django 2.2.1 on 2019-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image_small',
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='item_images', verbose_name='Изображение товара'),
        ),
    ]
